import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import React, { useState, useEffect  } from 'react';
import Link from 'next/link'
import Leftdiv from './ass/Leftdiv';
import Topbar from './ass/Topbar';


export default function public_user() {


    const handleSubmit = async (event) => {
    // Stop the form from submitting and refreshing the page.
    event.preventDefault()

    // Get data from the form.
    const data = {
      first: event.target.first.value,      
      roll: event.target.roll.value,
    }
    const JSONdata = JSON.stringify(data)
    console.log(JSONdata)
  }



  const uploadToClient = (event) => {
      if (event.target.files && event.target.files[0]) {
        const yes = event.target.files[0];
        console.log(yes, 88)
      }

      
  };

  


  return (
    <>
      <Head>
        <title>Shikhon School_public_quize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      

   <>   
                 

                 <Topbar/>


 
      <div className="main">
          <div className="left_side">
         <Leftdiv/>
         </div>



        <div className="right_side">

          <form onSubmit={handleSubmit}>
            <label htmlFor="first">First Name</label>
            <input type="text" name="first" required />

            <label htmlFor="last">Last Name</label>
            <input type="file" name="myImage" onChange={uploadToClient} />

            <label htmlFor="last">Numbers of Rool</label>
            <input type="text" name="roll" required minLength="10" maxLength="20"/>

            <button type="submit">Submit</button>
          </form>

        </div>

      </div>


    

</>
    </>
  )
}
