import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import React, { useState, useEffect  } from 'react';
import Link from 'next/link'
import Leftdiv from './ass/Leftdiv';
import Topbar from './ass/Topbar';
import { useForm } from 'react-hook-form';
import axios from 'axios';





export default function setting() {
      const [view, setView] = useState(null);
      const [photo, setPhoto] = useState();
      const [cureentphoto, setCureentphoto] = useState();



 const changePhotoHandaller = (file) => {
        setPhoto(file[0]);
    }



    async function createPost(e) {
        e.preventDefault()
        if(photo){

        var formData = new FormData();
        formData.append('file', photo);
        
        await axios.post('/api/quizecatagory', formData)
            .then(response => {
                console.log(response.data.data);              
                setCureentphoto(response.data.data);              
            })

        }else{
          console.log("data not fundd")
        }
    }




 


  return (
    <>
      <Head>
        <title>Shikhon School-quize_catagory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main>       
               

<Topbar/>

 
      <div className="main">
          <div className="left_side">
         <Leftdiv/>
         </div>



        <div className="right_side">
          quize_catagory<br/>  

        <form method="POST" onSubmit={createPost}>                   
          <input name='file' type='file' onChange={(e) => changePhotoHandaller(e.target.files)} />
          <button>Sending</button>                 
        </form>

{cureentphoto ? <Image src={`/uploads/${cureentphoto}`} alt="img not show" width="100" height="100" /> : ""}
        </div>

      </div>


      </main>


    </>
  )
}
